// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDAlC8Tw_8HtIbnEVXEVp4y15RI84tXqY',
    appId: '1:367773996626:android:f1b5c2e67339b5f3f4718b',
    messagingSenderId: '367773996626',
    projectId: 'video-player-ee4bc',
    storageBucket: 'video-player-ee4bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVjPO9r9xtUmdpSCpgYlIIgfIyDRVx-O0',
    appId: '1:367773996626:ios:1722a115f7d0f808f4718b',
    messagingSenderId: '367773996626',
    projectId: 'video-player-ee4bc',
    storageBucket: 'video-player-ee4bc.appspot.com',
    androidClientId: '367773996626-hsluncad7mndbpabr286cs9oto2m7it3.apps.googleusercontent.com',
    iosClientId: '367773996626-9na25dkp89aek6iu1942f10m52h90983.apps.googleusercontent.com',
    iosBundleId: 'com.example.lilacMachineTest',
  );
}
